### ISSUE TITLE
Better styles for the demo page

### ISSUE THREAD

**Issue by michael** [cutting-room-floor/spots#2]
Maybe it should feature the installation instructions as well, we could put them right below the example map.

What needs to be improved:
- A proper header would be nice
- Prominent links for download (linking to the file on Github and a minimized version)
- The Pins listing on the right
- Credits  (Contributor names + A MapBox project) ?

Long story short, it should just be pretty. And once we're ready this could be a blogpost on MapBox.com?

/cc @gundersen @tmcw any thoughts?

**Comment by tmcw** [comment]
Closing this to split up into sub-tickets
