### ISSUE TITLE
Overlay style suggestion

### ISSUE THREAD

**Issue by michael** [cutting-room-floor/spots#4]
Instead of pins, we could use badges like this (including icons)

![image](http://substance-assets.s3.amazonaws.com/c0/fc0e1bf26323c456c46ab6d346aa94/pinpoint.png)

If you click on a badge, it just gets surrounded by an info box.. the icon itself stays on the exact same location and it's turned into something like a business card.

Thoughts? /cc @tmcw @tristen @gundersen @yhahn @lxbarth @ajashton

**Comment by gundersen** [comment]
@michael this is really cool.

**Comment by michael** [comment]
Okay, further refinements. We might want to have the details sticky, for a more pleasant, less obtrusive user experience. 

![image](http://substance-assets.s3.amazonaws.com/b3/154032e7d2815df7de6575ed42ebf9/pinpoint-selected-poi.png)

Also if no spot is selected, we can show a list of spots (annotations) at the bottom. They're ordered chronologically, in order to tell a story ("Eg.: on my trip to Austria I've been to Spot A, B, C, D"). Users may also want to flip through the spots one by one, having the map centered at the currently selected one.

![image](http://substance-assets.s3.amazonaws.com/08/43cb558428a554300660d5aceff6d0/pinpoint-no-selection.png)

I like the term "Spot" over "Pin". So I'd consider renaming this from Pinpoint™ to Spot™ or Spots™? Thoughts?

@gundersen I'd actually want to move the repository to mapbox/pinpoint sooner than later, should I?

/cc @tmcw @tristen @yhahn @lxbarth @ajashton @samanpwbb

**Comment by willwhite** [comment]
Awesome @michael. I love how this is looking. Feel free to move this repo to mapbox and let me know if you need a hand with that.

**Comment by michael** [comment]
@willwhite Yeah, done. Calling this MapBox Spot™ now to test out how this term feels on the tongue. ;)
